auto: true
save: true
pygments: true
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: rdiscount
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]
